# Generated by Django 4.2.8 on 2024-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('resume', models.FileField(upload_to='uploads/')),
                ('profile_image', models.ImageField(blank=True, default=None, upload_to='uploads/')),
                ('cover_letter', models.FileField(blank=True, default='None', upload_to='uploads/')),
                ('social_profile', models.URLField(blank=True, default=None)),
                ('github_profile', models.URLField(blank=True, default=None)),
                ('website', models.URLField(blank=True, default=None)),
                ('skills', models.TextField()),
                ('ac', models.BooleanField(default=True, verbose_name='Accept the terms and conditions')),
            ],
        ),
    ]
